# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countSNPs_cpp <- function(POS, windowSize) {
    .Call('_QTLseqr_countSNPs_cpp', PACKAGE = 'QTLseqr', POS, windowSize)
}

