# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count number of SNPs within a sliding window
#' 
#' For each SNP returns how many SNPs are bracketing it within the set window size
#' 
#' @param POS A numeric vector of genomic positions for each SNP
#' @param windowSize The required window size
#' @export countSNPs_cpp
countSNPs_cpp <- function(POS, windowSize) {
    .Call('_QTLseqr_countSNPs_cpp', PACKAGE = 'QTLseqr', POS, windowSize)
}

